[project]
name = "uv1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "openai-agents>=0.0.19",
    "python-decouple>=3.8",
    "uvicorn>=0.34.3",
]
